### ISSUE TITLE
CRUD not select information from vshard

### ISSUE THREAD

**Issue by seet61** [tarantool/crud#135]
We have cartridge application.

```
dependencies = {
        'tarantool == 2.5.3',
        'lua >= 5.1',
        'checks',
    'cartridge == 2.5.0',
    'metrics == 0.7.0',
    'cartridge-cli-extensions',
    'crud == 0.5.0',
    'http',
    'gis',
}
```

At storage role we have space:
```
        -- authTemplates
        local authTemplates_space = box.schema.space.create('authTemplates', {
            engine = 'memtx',
            if_not_exists = true,
        })
        log.info('authTemplates space was configured')

        authTemplates_space:format({
            {name='msisdn',type='string'},
            {name='channel',type='string'},
            {name='password',type='string'},
            {name='counter',type='unsigned'},
            {name='create_date',type='unsigned'},
            {name='ttl',type='unsigned'},
            {name='bucket_id', type='unsigned'},
        })
        log.info('authTemplates was formatted')

        authTemplates_space:create_index('authTemplates_msisdn_channel_idx', {parts={{field='msisdn'}, {field='channel'}},
            type = 'HASH',
            if_not_exists=true})
        log.info('authTemplates_msisdn_channel_idx')

        authTemplates_space:create_index('bucket_id', {parts={{field='bucket_id'}},
            unique=false,
            if_not_exists=true})
        log.info('authTemplates_bucket_id')

        authTemplates_space:create_index('ttl', {parts={{field='ttl'}},
            unique=false,
            if_not_exists=true})
        log.info('authTemplates_ttl')
```

Topology:
We have 2 servers.
At each server started 3 roles: router, master and replica.

3 replica set: for router and 2 storages. Master storage reserving by replica from another server.
![image](https://user-images.githubusercontent.com/6140289/112429891-6536fc80-8d4e-11eb-8225-f172ff51d901.png)

Saving this entry by crud:
```
{"1":"79774120882","2":"app4t2","3":"671418","4":3,"5":1716591611,"6":1716592211,"space":"authTemplates"}


crud.insert('authTemplates', {"1":"79774120882","2":"app4t2","3":"671418","4":3,"5":1716591611,"6":1716592211}, {timeout = 5})
```

After that we trying to get this information from first router:
```
localhost:3301> crud.select('authTemplates', {{'==', 'authTemplates_msisdn_channel_idx', {'79774120882', 'app4t2'}}}, {timeout = 5})
---
- metadata: [{'name': 'msisdn', 'type': 'string'}, {'name': 'channel', 'type': 'string'},
    {'name': 'password', 'type': 'string'}, {'name': 'counter', 'type': 'unsigned'},
    {'name': 'create_date', 'type': 'unsigned'}, {'name': 'ttl', 'type': 'unsigned'},
    {'name': 'bucket_id', 'type': 'unsigned'}]
  rows: []
...

localhost:3301> crud.select('authTemplates', {{'==', 'authTemplates_msisdn_channel_idx', {'79774120882'}}}, {timeout = 5})
---
- metadata: [{'name': 'msisdn', 'type': 'string'}, {'name': 'channel', 'type': 'string'},
    {'name': 'password', 'type': 'string'}, {'name': 'counter', 'type': 'unsigned'},
    {'name': 'create_date', 'type': 'unsigned'}, {'name': 'ttl', 'type': 'unsigned'},
    {'name': 'bucket_id', 'type': 'unsigned'}]
  rows:
  - ['79774120882', 'app4t2', '671418', 3, 1716591611, 1716592211, 21401]
...

```

from second router:
```
localhost:3301> crud.select('authTemplates', {{'==', 'authTemplates_msisdn_channel_idx', {'79774120882', 'app4t2'}}}, {timeout = 5})
---
- metadata: [{'name': 'msisdn', 'type': 'string'}, {'name': 'channel', 'type': 'string'},
    {'name': 'password', 'type': 'string'}, {'name': 'counter', 'type': 'unsigned'},
    {'name': 'create_date', 'type': 'unsigned'}, {'name': 'ttl', 'type': 'unsigned'},
    {'name': 'bucket_id', 'type': 'unsigned'}]
  rows:
  - ['79774120882', 'app4t2', '671418', 3, 1716591611, 1716592211, 21401]
...

localhost:3301> crud.select('authTemplates', {{'==', 'authTemplates_msisdn_channel_idx', {'79774120882'}}}, {timeout = 5})
---
- metadata: [{'name': 'msisdn', 'type': 'string'}, {'name': 'channel', 'type': 'string'},
    {'name': 'password', 'type': 'string'}, {'name': 'counter', 'type': 'unsigned'},
    {'name': 'create_date', 'type': 'unsigned'}, {'name': 'ttl', 'type': 'unsigned'},
    {'name': 'bucket_id', 'type': 'unsigned'}]
  rows:
  - ['79774120882', 'app4t2', '671418', 3, 1716591611, 1716592211, 21401]

```

Why it so different?

Alsough CRUD can save it twice to each replica set with storage. This is bad because index for unicue.

**Comment by seet61** [comment]
We check code of storage. Problem exist at type 'HASH' and TREE.
This example from dev when we trying to check different types of index.

authTemplates_space:create_index('authTemplates_msisdn_channel_idx', {parts={{field='msisdn'}, {field='channel'}},
            type = 'HASH',
            if_not_exists=true})
        log.info('authTemplates_msisdn_channel_idx')

At production:
![image](https://user-images.githubusercontent.com/6140289/113543022-317d9180-95ee-11eb-80ae-c7dd2d00e4a5.png)

**Comment by seet61** [comment]
Addition information from masters, replicas and routers. 
[box_info.txt](https://github.com/tarantool/crud/files/6256776/box_info.txt)

**Comment by filonenko-mikhail** [comment]
Seems that topology crossed somewhere  
```
s1-master
localhost:3302> box.space['authTemplates']:select({'79774120882'})
[]
s1-replica
localhost:3303> box.space['authTemplates']:select({'79774120882'})
['79774120882', 'app4t2', '671418', 3, 1716591611, 1716592211, 14899]

s2-master
localhost:3302> box.space['authTemplates']:select({'79774120882'})
['79774120882', 'app4t2', '671418', 3, 1716591611, 1716592211, 14899]
s2-replica
box.space['authTemplates']:select({'79774120882'})
[]

```

**Comment by seet61** [comment]
router.info() from two instances with router role. 

s1-router
```
localhost:3301> vshard.router.info()
---
- replicasets:
    7bdcd8e6-9258-4018-958e-aec2dc8bcca8:
      replica: &0
        network_timeout: 0.5
        status: available
        uri: admin@10.12.75.147:3302
        uuid: 33f039f2-e904-484b-8b92-1def624b6c06
      bucket:
        available_rw: 15000
      uuid: 7bdcd8e6-9258-4018-958e-aec2dc8bcca8
      master: *0
    2133bd7a-5d61-4b51-b5ba-a6c5a4324d36:
      replica: &1
        network_timeout: 0.5
        status: available
        uri: admin@10.12.75.146:3302
        uuid: 020fba9c-8510-444b-9278-44f1cf4c1ec9
      bucket:
        available_rw: 15000
      uuid: 2133bd7a-5d61-4b51-b5ba-a6c5a4324d36
      master: *1
  bucket:
    unreachable: 0
    available_ro: 0
    unknown: 0
    available_rw: 30000
  status: 0
  alerts: []
```


s2-router
```
localhost:3301> vshard.router.info()
---
- replicasets:
    7bdcd8e6-9258-4018-958e-aec2dc8bcca8:
      replica: &0
        network_timeout: 0.5
        status: available
        uri: admin@10.12.75.147:3302
        uuid: 33f039f2-e904-484b-8b92-1def624b6c06
      bucket:
        available_rw: 15000
      uuid: 7bdcd8e6-9258-4018-958e-aec2dc8bcca8
      master: *0
    2133bd7a-5d61-4b51-b5ba-a6c5a4324d36:
      replica: &1
        network_timeout: 0.5
        status: available
        uri: admin@10.12.75.146:3302
        uuid: 020fba9c-8510-444b-9278-44f1cf4c1ec9
      bucket:
        available_rw: 15000
      uuid: 2133bd7a-5d61-4b51-b5ba-a6c5a4324d36
      master: *1
  bucket:
    unreachable: 0
    available_ro: 0
    unknown: 0
    available_rw: 30000
  status: 0
  alerts: []
...
```
